#pragma once

#include "NativeGameplayTags.h"

namespace AlsLocomotionActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(M4)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}
